### ISSUE TITLE
Moving Page Node

### ISSUE THREAD

**Issue by c0ber** [Kunstmaan/KunstmaanBundlesStandardEdition#118]
Hi,

I have question about moving Pages.  I want to be as clear as possible.

To draw an example lets make some abstract names:
ThePage - page we want to move
ParentPage - page of which ThePage was created as subpage
Home - Master level page

Tree:
| Home
|---| ParentPage
|---|---| ThePage

Now I want to move ThePage to Home node so tree would look like:
| Home
|---| ParentPage
|---| ThePage

Now there is no such functionality, however I managed to do this easily by editing row in kuma_nodes table (changed the parent_id and lvl for ThePage page node to appropriate ones).

Are you planning to add functionality to move pages between nodes (of course between nodes that can have such subpage types)? If not I would have probably implement it by myself. I would appreciate any kind of suggestion on implementation.

**Comment by bobemoe** [comment]
Me too, totally need this vital functionality.. keep me updated, might be able to lend a hand implementing. I'll share any ideas here if i attempt this.

**Comment by roderik** [comment]
Well, we are planning it, mostly in https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/68 but before we can, we got some stuff to do. Fro the 3.1 release by end of march we will upgrade the backend to Bootstrap 3, and at the same time upgrade the jstree. We are however not adding new features to the tree yet, since this backend rework combined with a complete overhaul of the generator for the default site is a big chunk. It will however be a good starting point for implementing this feature, either by us, or someone else.

**Comment by bobemoe** [comment]
I have made a simple console command to allow changing parents of a node on v2.  Its in my KumaBundle: https://github.com/bobemoe/JHodgesKumaBundle

**Comment by krispypen** [comment]
@bobemoe you can use drag and drop in the admin tree
